### ISSUE TITLE
Can it be used in umbrella project  or in distributed system ?

### ISSUE THREAD

**Issue by r8code** [otobus/event_bus#121]
Hi , I want to ask :
can it be used in umbrella project ? if can  what config or setting I should set ?
can it also be used in distributed system ?
Thank you

**Comment by mustafaturan** [comment]
Hi @r8code 

It is possible to use `event_bus` library in umbrella project. Currently, because of my busy schedule, I can't provide a documentation but it is very close to run it on any single project. For distributed system part, it really depends on your design. I recommend reading the last section of the Medium story https://medium.com/elixirlabs/decoupled-modules-with-elixir-eventbus-a709b1479411#770e 

Just as a side note, I am closing the issue since it is closer to the consultancy rather than issue. 
Thank you for using `event_bus` 🏄

**Comment by r8code** [comment]
Thank you for the library ,
the article gives the clue.
