### ISSUE TITLE
Dynamic listeners?

### ISSUE THREAD

**Issue by madshargreave** [otobus/event_bus#64]
Hi

Is it not possible to register an arbitrary process as a listener using its PID? If I've understood the current implementation correctly, then each subscriber has to be implemented as a named module

**Comment by mustafaturan** [comment]
Hi @madshargreave,

It is possible to set pid as a listener using configurable listeners(but you might prefer to pg2 instead of event_bus):

1- you will need to create a configurable listener using a module and then inside that module you can use the ‘pid’ to do whatver you want 
2- when the process dies, then you should have to unsubscribe that module

I shared some samples for you

sample module with conf: 
https://github.com/mustafaturan/sse/blob/master/lib/sse.ex#L11

sample dynamic subscription for pid: https://github.com/mustafaturan/sse/blob/master/lib/sse/server.ex#L17


sample dynamic unsubscription of a pid: https://github.com/mustafaturan/sse/blob/master/lib/sse/server.ex#L63

Let me know if you need help
