### ISSUE TITLE
Tracing Causation

### ISSUE THREAD

**Issue by ShaneWilton** [otobus/event_bus#77]
Currently, EventBus supports setting a `transaction_id` on events, in order to trace chains of related events. This works for determining what events are correlated, but is insufficient for reconstructing the precise causal relationships between events.

Imagine the following series of events:

```
       /-> C -> D
A -> B 
       \-> E
``` 

As currently implemented, all of the above events will have the same `transaction_id`, and so are obviously correlated. It is not possible, however, to determine that `D` was caused by `C`, which was caused by `B`, and so on.

One possible solution to this would be extending the event schema to include an additional field for `causation_id`, which could be set to the `id` of the previous event in the chain. This is a pattern described by Greg Young in his definition of Event Sourcing. Another explanation is available here: https://blog.arkency.com/correlation-id-and-causation-id-in-evented-systems/

The existing `transaction_id` field fills effectively the same role as the `correlation_id`, and doesn't need to be changed in my opinion :)

What are your thoughts on this proposal?

**Comment by mustafaturan** [comment]
Hey @ShaneWilton 

I read the article but IMHO it is unnecessary in the following condition;
It is possible to find that event using `transaction_id`(corresponds to `correlation_id`) and topic(corresponds to `causation_id`). When you provide those 2 values to a query system you can find any event. Please note that event topic names should be unique in this case. And all consumers should be responsible only from one event topic. 

Because while implementing event consumers, we should conside two basic things: 
- Each event consumer should be responsible from only one event 
  - Except the catch all ones(generic consumers like `event_bus_logger` or `event_bus_postgres`)
- An event should be consumable more than one consumer when necessary
- Event should provide `transaction_id`

I recommend checking out `event_bus_postgres` library and use sql to query desired events using `transaction_id`. I think that may help you to cover your case.

But would love to hear more opinions and thoughts

Thanks for bringing

**Comment by ShaneWilton** [comment]
Hi @mustafaturan!

I'm responding from my phone, and it's possible I'm misunderstanding you, but I can imagine an scenario where those assumptions don't hold.

Imagine a fan-out situation, where one event causes 3 events of the same type to be emitted, over the same topic, and each of those cause a subsequent event. There will then be 3 chains fanning out from the first event, but it is no longer possible to determine which event is the predecessor of one of the leaves, since they will all have been emitted over the same topic (being the same type of event), and as part of the same transaction.

As a concrete example, imagine that a user purchases all of the items in their shopping cart. An ItemPurchased event is then emitted for each of the 3 items purchased. Once each of those events is processed, an OrderFulfilled event is emitted.

Using only the transaction_id and the topic, it is not possible to associate the OrderFulfilled event with it's corresponding ItemPurchased event.

Let me know if that makes sense or if I'm missing something :) I can try to clarify more when I have access to a computer if you'd like.

**Comment by mustafaturan** [comment]
| id | transaction_id | topic                | data |
| -- | -------------- | ---------------------| ---- |
|  1 | t1             | :item_purchased      | ...  |
|  2 | t1             | :email_sent          | ...  |
|  3 | t1             | :stats_updated       | ...  |
|  4 | t1             | :cargo_label_created | ...  |
|  5 | t1             | :order_fullfilled    | ...  |

```elixir
defmodule OrderFulfiller do
  def proces({:cargo_label_created, id}) do
    ...
    event = %Event{topic: :order_fullfilled, id: 6, data: "..."}
    Event.notify(event)
  end
end
```

Since the `OrderFulfiller` knows the what to listen in this case `:cargo_label_created` you can query event id of `cargo_label_created` which caused `order_fullfilled` event.

**Comment by mustafaturan** [comment]
In my sample above; the `OrderFulfiller ` is only responsible from one event topic

**Comment by ShaneWilton** [comment]
Sorry, I think I wasn't being clear about the scenario I'm talking about :) What you're describing makes sense, and I can understand how using the topic to determine causality would work. The difference is that in the situation I'm talking about, it is possible for more than one instance of an event to be emitted as a result of another.

Here's some rough code to demonstrate:

```elixir
defmodule OrderWorkflow do
  def purchase_shopping_cart(%Cart{items: items}) do
    ...
    
    transaction_id = UUID.uuid4()
    
    Enum.each(items, fn item ->
      %Event{topic: :item_purchased, transaction_id: transaction_id, data: ...}
      |> EventBus.notify()
    end)
  end

  def process({:item_purchased, id}) do
    ...
    %Event{topic: :cargo_label_created, transaction_id: transaction_id, data: ...}
    |> EventBus.notify()
  end

  def process({:cargo_label_created, id}) do
    ...
    %Event{topic: :order_fulfilled, transaction_id: transaction_id, data: ...}
    |> EventBus.notify()
  end
end

OrderWorkflow.purchase_shopping_cart(%Cart{items: [%Item{}, %Item{}, %Item{}]})
```

Here, the call to `purchase_shopping_cart` results in 3 `:item_purchased` events, which results in 3 `:cargo_label_created` events, and 3 `:order_fulfilled` events. All events have the same `transaction_id`, and events of the same type will share the same topic. Given a `:order_fulfilled` event, I cannot determine which `:cargo_label_created` event caused it, because there are 3 possibilities that match the correct `transaction_id` and topic.

Does that make sense?
